// Mocks generated by Mockito 5.1.0 from annotations
// in ditonton/test/domain/usecases/get_tv_watchlist_status_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:ditonton/common/failure.dart' as _i5;
import 'package:ditonton/domain/entities/tv/tv.dart' as _i6;
import 'package:ditonton/domain/entities/tv/tv_detail.dart' as _i7;
import 'package:ditonton/domain/repositories/tv_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [TvRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRepository extends _i1.Mock implements _i3.TvRepository {
  MockTvRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvSeries>>> getNowPlayingTVs() =>
      (super.noSuchMethod(Invocation.method(#getNowPlayingTVs, []),
              returnValue:
                  Future<_i2.Either<_i5.Failure, List<_i6.TvSeries>>>.value(
                      _FakeEither_0<_i5.Failure, List<_i6.TvSeries>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvSeries>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvSeries>>> getPopularTvs() =>
      (super
              .noSuchMethod(Invocation.method(#getPopularTvs, []),
                  returnValue:
                      Future<_i2.Either<_i5.Failure, List<_i6.TvSeries>>>.value(
                          _FakeEither_0<_i5.Failure, List<_i6.TvSeries>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvSeries>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.TvDetail>> getTvDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvDetail, [id]),
              returnValue: Future<_i2.Either<_i5.Failure, _i7.TvDetail>>.value(
                  _FakeEither_0<_i5.Failure, _i7.TvDetail>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i7.TvDetail>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> saveWatchlist(
          _i7.TvDetail? detail) =>
      (super.noSuchMethod(Invocation.method(#saveWatchlist, [detail]),
              returnValue: Future<_i2.Either<_i5.Failure, String>>.value(
                  _FakeEither_0<_i5.Failure, String>()))
          as _i4.Future<_i2.Either<_i5.Failure, String>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> removeWatchlist(
          _i7.TvDetail? detail) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [detail]),
              returnValue: Future<_i2.Either<_i5.Failure, String>>.value(
                  _FakeEither_0<_i5.Failure, String>()))
          as _i4.Future<_i2.Either<_i5.Failure, String>>);
  @override
  _i4.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedToWatchlist, [id]),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvSeries>>>
      getWatchlistMovies() =>
          (super.noSuchMethod(Invocation.method(#getWatchlistMovies, []),
                  returnValue:
                      Future<_i2.Either<_i5.Failure, List<_i6.TvSeries>>>.value(
                          _FakeEither_0<_i5.Failure, List<_i6.TvSeries>>()))
              as _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvSeries>>>);
}
